### ISSUE TITLE
Do not serialize default values

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#558] opened 2023-03-03 09:26 UTC
### Please describe the feature that you want to propose

When a property is set to  its default value, it should not be serialized otherwise it ends up with a very large file which is hard to read.

it happens after we modify one of the values to a non default value

For instance for log:

![image](https://user-images.githubusercontent.com/1105127/222682894-088b6dfc-e4d7-4490-95fc-0c178f28ff5a.png)

additional: it can be convenient to have a setting to allow keeping these values too.

**Comment by Delawen** [comment] 2023-03-21 11:09
Closing as duplicate of #503

**Closed by Delawen** 2023-03-21 11:09 UTC
